#!/usr/bin/env python3
"""Generate browser and server display-contract constants from schemas/*.json.

The JSON files are the product boundary. Do not hand-edit src/generated/display-contract.js
or scripts/generated/display_contract.py.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas"
JS_OUT = ROOT / "src/generated/display-contract.js"
PY_OUT = ROOT / "scripts/generated/display_contract.py"

def load(name: str) -> dict:
    return json.loads((SCHEMAS / name).read_text(encoding="utf-8"))

def main() -> None:
    presets_doc = load("hermes-display-presets.json")
    optic_doc = load("hermes-optic-postures.json")
    state_schema = load("hermes-display-state.schema.json")
    event_schema = load("hermes-avatar-event.schema.json")
    optic_schema = load("hermes-optic-state.schema.json")
    presets = presets_doc["presets"]
    labels = {key: value["label"] for key, value in presets.items()}
    motion = {key: value["motion"] for key, value in presets.items()}
    payload = {
        "DISPLAY_PRESETS": presets,
        "DISPLAY_PRESET_LABELS": labels,
        "DISPLAY_PRESET_MOTION": motion,
        "OPTIC_MODE_BY_PRESET": optic_doc["optic_mode_by_preset"],
        "OPTIC_STATE_BY_MODE": optic_doc["optic_state_by_mode"],
        "SCHEMAS": {
            "display_state": state_schema,
            "avatar_event": event_schema,
            "optic_state": optic_schema,
        },
    }
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    js_json = json.dumps(payload, indent=2, sort_keys=True)
    JS_OUT.write_text(
        "// Generated by scripts/generate_display_contract.py; do not edit by hand.\n"
        "(() => {\n"
        f"  const contract = {js_json};\n"
        "  if (typeof window !== 'undefined') window.HermesDisplayContract = Object.freeze(contract);\n"
        "})();\n",
        encoding="utf-8",
    )
    py_json = json.dumps(payload, indent=2, sort_keys=True)
    PY_OUT.write_text(
        "# Generated by scripts/generate_display_contract.py; do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        "import json\n\n"
        f"_CONTRACT = json.loads({py_json!r})\n\n"
        "DISPLAY_PRESETS = _CONTRACT['DISPLAY_PRESETS']\n"
        "DISPLAY_PRESET_LABELS = _CONTRACT['DISPLAY_PRESET_LABELS']\n"
        "DISPLAY_PRESET_MOTION = _CONTRACT['DISPLAY_PRESET_MOTION']\n"
        "OPTIC_MODE_BY_PRESET = _CONTRACT['OPTIC_MODE_BY_PRESET']\n"
        "OPTIC_STATE_BY_MODE = _CONTRACT['OPTIC_STATE_BY_MODE']\n"
        "DISPLAY_CONTRACT_SCHEMAS = _CONTRACT['SCHEMAS']\n",
        encoding="utf-8",
    )

if __name__ == "__main__":
    main()
