#!/usr/bin/env python3
"""Generate browser and server display-contract constants from schemas/*.json.

The JSON files are the product boundary. Do not hand-edit src/generated/display-contract.js
or scripts/generated/display_contract.py.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas"
JS_OUT = ROOT / "src/generated/display-contract.js"
PY_OUT = ROOT / "scripts/generated/display_contract.py"

def load(name: str) -> dict:
    return json.loads((SCHEMAS / name).read_text(encoding="utf-8"))

def build_payload() -> dict:
    presets_doc = load("hermes-display-presets.json")
    optic_doc = load("hermes-optic-postures.json")
    state_schema = load("hermes-display-state.schema.json")
    event_schema = load("hermes-avatar-event.schema.json")
    optic_schema = load("hermes-optic-state.schema.json")
    presets = presets_doc["presets"]
    labels = {key: value["label"] for key, value in presets.items()}
    motion = {key: value["motion"] for key, value in presets.items()}
    return {
        "DISPLAY_PRESETS": presets,
        "DISPLAY_PRESET_LABELS": labels,
        "DISPLAY_PRESET_MOTION": motion,
        "OPTIC_MODE_BY_PRESET": optic_doc["optic_mode_by_preset"],
        "OPTIC_STATE_BY_MODE": optic_doc["optic_state_by_mode"],
        "SCHEMAS": {
            "display_state": state_schema,
            "avatar_event": event_schema,
            "optic_state": optic_schema,
        },
    }


def render_outputs(payload: dict) -> dict[Path, str]:
    js_json = json.dumps(payload, indent=2, sort_keys=True)
    py_json = json.dumps(payload, indent=2, sort_keys=True)
    return {
        JS_OUT: "// Generated by scripts/generate_display_contract.py; do not edit by hand.\n"
        "(() => {\n"
        f"  const contract = {js_json};\n"
        "  if (typeof window !== 'undefined') window.HermesDisplayContract = Object.freeze(contract);\n"
        "})();\n",
        PY_OUT: "# Generated by scripts/generate_display_contract.py; do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        "import json\n\n"
        f"_CONTRACT = json.loads({py_json!r})\n\n"
        "DISPLAY_PRESETS = _CONTRACT['DISPLAY_PRESETS']\n"
        "DISPLAY_PRESET_LABELS = _CONTRACT['DISPLAY_PRESET_LABELS']\n"
        "DISPLAY_PRESET_MOTION = _CONTRACT['DISPLAY_PRESET_MOTION']\n"
        "OPTIC_MODE_BY_PRESET = _CONTRACT['OPTIC_MODE_BY_PRESET']\n"
        "OPTIC_STATE_BY_MODE = _CONTRACT['OPTIC_STATE_BY_MODE']\n"
        "DISPLAY_CONTRACT_SCHEMAS = _CONTRACT['SCHEMAS']\n",
    }


def check_outputs(outputs: dict[Path, str]) -> bool:
    def display_path(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT))
        except ValueError:
            return str(path)

    stale: list[str] = []
    for path, expected in outputs.items():
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            stale.append(f"missing: {display_path(path)}")
            continue
        if current != expected:
            stale.append(f"stale: {display_path(path)}")

    if stale:
        print("Generated display contract is out of date:")
        for item in stale:
            print(f"  - {item}")
        print("Run: npm run generate:contract")
        return False

    print("Generated display contract is current.")
    return True


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate display-contract constants from schemas/*.json.")
    parser.add_argument("--check", action="store_true", help="verify generated files are current without rewriting them")
    args = parser.parse_args()

    outputs = render_outputs(build_payload())
    if args.check:
        raise SystemExit(0 if check_outputs(outputs) else 1)

    write_outputs(outputs)

if __name__ == "__main__":
    main()
