(() => {
  const BROWS = {
    flat_left:              'M -22 -20 L 21 -20',
    flat_right:             'M -21 -20 L 22 -20',
    neutral_left:           'M -22 -19 Q -2 -22 21 -20',
    neutral_right:          'M -21 -20 Q 2 -22 22 -19',
    skeptical_left:         'M -22 -18 L 21 -22',
    skeptical_right:        'M -21 -22 L 22 -18',
    raised_left:            'M -22 -22 Q -2 -28 21 -23',
    raised_right:           'M -21 -23 Q 2 -28 22 -22',
    popped_left:            'M -22 -25 Q -2 -32 21 -26',
    popped_right:           'M -21 -26 Q 2 -32 22 -25',
    angry_left:             'M -22 -22 L 21 -13',
    angry_right:            'M -21 -13 L 22 -22',
    annoyed_left:           'M -22 -19 L 21 -13',
    annoyed_right:          'M -21 -13 L 22 -19',
    squint_focused_left:    'M -22 -18 Q -2 -14 21 -17',
    squint_focused_right:   'M -21 -17 Q 2 -14 22 -18',
    sleepy_low_left:        'M -22 -15 Q -2 -13 21 -15',
    sleepy_low_right:       'M -21 -15 Q 2 -13 22 -15',
    smug_arch_left:         'M -22 -18 L 21 -20',
    smug_arch_right:        'M -21 -22 Q 2 -28 22 -20',
    worried_left:           'M -22 -14 L 21 -22',
    worried_right:          'M -21 -22 L 22 -14',
    side_eye_squint_left:   'M -22 -18 Q -2 -12 21 -16',
    side_eye_squint_right:  'M -21 -16 Q 2 -12 22 -18'
  };

  const MOUTH_PATHS = {
    neutral:           'M -23 31 C -12 28 -7 34 0 31 C 7 28 12 34 23 31',
    smile_small:       'M -16 30 Q 0 38 16 30',
    smile_wide:        'M -20 28 Q 0 42 20 28',
    smile_smug:        'M -20 32 Q -4 26 18 31',
    smirk_left:        'M -20 33 Q -4 26 20 33',
    smirk_right:       'M -20 33 Q 4 26 20 33',
    flat:              'M -18 31 L 18 31',
    flat_tight:        'M -13 31 L 13 31',
    flat_focus:        'M -16 31 L 16 31',
    frown_small:       'M -16 33 Q 0 26 16 33',
    annoyed_flatwave:  'M -18 31 Q -10 34 0 30 Q 10 27 18 31',
    ohh_small:         'M -6 28 Q 0 36 6 28 Q 0 27 -6 28',
    yawn_oval:         'M -9 27 Q 0 39 9 27 Q 0 29 -9 27',
    sleepy_line:       'M -11 31 Q 0 33 11 31',
    drowsy_droop:      'M -14 31 Q -4 35 0 32 Q 4 29 14 31',
    thinking_zigzag:   'M -20 31 C -12 27 -8 36 0 31 C 8 26 14 33 20 28',
    side_smirk:        'M -20 31 C -8 29 4 36 20 29',
    open_surprise:     'M -8 26 Q 0 40 8 26 Q 0 30 -8 26'
  };

  const GAZE = {
    center:         { x:  0.0, y:  0.0 },
    left:           { x: -5.6, y:  0.2 },
    right:          { x:  5.6, y:  0.2 },
    up:             { x:  0.0, y: -2.4 },
    down:           { x:  0.0, y:  2.0 },
    up_left:        { x: -5.4, y: -1.8 },
    up_right:       { x:  5.4, y: -1.8 },
    down_left:      { x: -5.4, y:  1.8 },
    down_right:     { x:  5.4, y:  1.8 },
    side_eye_left:  { x: -9.4, y:  1.3 },
    side_eye_right: { x:  9.4, y:  1.3 },
    forward_focus:  { x:  0.0, y: -0.8 },
    smug:           { x:  1.8, y: -1.1 },
    sleepy:         { x:  0.0, y:  2.0 }
  };

  const BEHAVIOR_GAZE_GRAMMAR = {
    idle_watch: ['center','forward_focus','left','right','sleepy'],
    reading: ['down','down_left','down_right','center'],
    searching: ['left','right','up_left','up_right','forward_focus','down_right'],
    tool_shell: ['down_right','right','down','forward_focus'],
    writing: ['down_right','forward_focus','right','center'],
    waiting: ['center','forward_focus','down'],
    blocked: ['forward_focus','side_eye_left','down_left','center'],
    complete: ['center','forward_focus','smug','right'],
    degraded_offline: ['down_left','center','down','left']
  };

  const BEHAVIOR_MOUTH_GRAMMAR = {
    idle_watch: 'neutral',
    reading: 'neutral',
    searching: 'ohh_small',
    tool_shell: 'flat_focus',
    writing: 'smirk_right',
    waiting: 'neutral',
    blocked: 'flat_tight',
    complete: 'smile_small',
    degraded_offline: 'drowsy_droop'
  };

  const CONTEXTUAL_BLINK_GRAMMAR = {
    notice: { durationMs: 120, double: false, lidDelta: -0.08 },
    orient: { durationMs: 145, double: false, lidDelta: 0.00 },
    commit: { durationMs: 95, double: false, lidDelta: 0.08 },
    sustain: { durationMs: 170, double: false, lidDelta: 0.03 },
    resolve: { durationMs: 190, double: true, lidDelta: 0.10 },
    degraded_offline: { durationMs: 320, double: false, lidDelta: 0.22 }
  };

  const STATES = {
    idle_watchful: {
      name: 'idle_watchful',
      label: 'IDLE WATCHFUL',
      blinkMs: [3800, 7600],
      doubleBlinkChance: 0.18,
      lid: 0.16,
      squint: 0.00,
      pupilScale: 1.00,
      irisScale: 1.00,
      browLeft: 'neutral_left',
      browRight: 'neutral_right',
      mouth: 'neutral',
      gazeTargets: ['center','forward_focus','center','left','right','down','center','sleepy'],
      gazeWeights: [7, 4, 5, 1, 1, 1, 5, 1],
      gazeDwellMs: [2600, 5600],
      gazeProfile: { saccadeMs: [115, 170], dwellMs: [2600, 5600], holdJitterPx: 0.055 },
      breath: 0.34,
      breathHz: 0.36,
      tailSway: 0.34,
      tailHz: 0.38,
      wingFlap: 0.11,
      wingHz: 0.34,
      wingRestDeg: -0.25,
      wingAsymmetryDeg: 0,
      wingTwitch: 0.18,
      wingLineBoost: 0.02,
      helmetTiltDeg: 0,
      bodyDriftX: 0.35,
      bodyDriftY: 0.0,
      driftHz: 0.32,
      motionBudget: { calm: true, rootXMax: 0.5, rootYMax: 1.0, tiltMax: 0.35 },
      fxIntensity: 0.42,
      eyeGlow: 0.36,
      browOpacity: 0.22,
      autoIntentMode: 'face_only',
      auraOpacity: 0.18,
      orbit: 0.38,
      spark: 0.20,
      runeIntensity: 0.18,
      scanBeam: false,
      intentPool: ['glance_left','glance_right','brow_pop','skeptical_squint','slow_blink'],
      intentWeights: [2, 2, 1, 1, 2],
      intentEveryMs: [12000, 22000]
    },
    thinking_focused: {
      name: 'thinking_focused',
      label: 'THINKING FOCUSED',
      blinkMs: [1600, 3600],
      doubleBlinkChance: 0.35,
      lid: 0.14,
      squint: 0.22,
      pupilScale: 0.78,
      irisScale: 1.00,
      browLeft: 'squint_focused_left',
      browRight: 'squint_focused_right',
      mouth: 'flat_focus',
      gazeTargets: ['up_left','up_right','forward_focus','right','up_left','left','down_right'],
      gazeWeights: [3, 2, 3, 1, 2, 1, 1],
      gazeDwellMs: [600, 1500],
      gazeProfile: { saccadeMs: [90, 135], dwellMs: [700, 1600], holdJitterPx: 0.10 },
      breath: 0.55,
      breathHz: 0.85,
      tailSway: 0.80,
      tailHz: 1.00,
      wingFlap: 0.45,
      wingHz: 1.40,
      wingRestDeg: 0.85,
      wingAsymmetryDeg: -0.45,
      wingTwitch: 0.42,
      wingLineBoost: 0.09,
      helmetTiltDeg: -3,
      bodyDriftX: 0.8,
      bodyDriftY: 0.3,
      driftHz: 0.42,
      motionBudget: { calm: false, rootXMax: 1.2, rootYMax: 1.6, tiltMax: 1.4 },
      fxIntensity: 1.0,
      eyeGlow: 0.68,
      browOpacity: 0.38,
      autoIntentMode: 'mixed',
      auraOpacity: 0.26,
      orbit: 1.10,
      spark: 0.85,
      runeIntensity: 0.55,
      scanBeam: true,
      intentPool: ['glance_left','glance_right','brow_pop','tiny_perk','scan_sweep','skeptical_squint'],
      intentWeights: [2, 2, 1, 1, 3, 1],
      intentEveryMs: [3000, 6500]
    },
    healthy_smug: {
      name: 'healthy_smug',
      label: 'HEALTHY SMUG',
      blinkMs: [3800, 7800],
      doubleBlinkChance: 0.10,
      lid: 0.18,
      squint: 0.14,
      pupilScale: 1.00,
      irisScale: 1.00,
      browLeft: 'smug_arch_left',
      browRight: 'smug_arch_right',
      mouth: 'smile_smug',
      gazeTargets: ['center','forward_focus','center','left','smug','right'],
      gazeWeights: [5, 4, 3, 2, 1, 1],
      gazeDwellMs: [2800, 5600],
      gazeProfile: { saccadeMs: [110, 165], dwellMs: [2800, 5600], holdJitterPx: 0.07 },
      breath: 0.32,
      breathHz: 0.34,
      tailSway: 0.40,
      tailHz: 0.42,
      wingFlap: 0.15,
      wingHz: 0.40,
      wingRestDeg: 0.25,
      wingAsymmetryDeg: 0.55,
      wingTwitch: 0.15,
      wingLineBoost: 0.04,
      helmetTiltDeg: 3,
      bodyDriftX: 0.25,
      bodyDriftY: 0.0,
      driftHz: 0.28,
      motionBudget: { calm: true, rootXMax: 0.3, rootYMax: 1.0, tiltMax: 0.45 },
      fxIntensity: 0.50,
      eyeGlow: 0.42,
      browOpacity: 0.30,
      autoIntentMode: 'face_only',
      auraOpacity: 0.20,
      orbit: 0.36,
      spark: 0.28,
      runeIntensity: 0.22,
      scanBeam: false,
      intentPool: ['glance_right','glance_left','brow_pop','slow_blink','skeptical_squint'],
      intentWeights: [2, 2, 1, 1, 1],
      intentEveryMs: [12000, 20000]
    },
    blocked_annoyed: {
      name: 'blocked_annoyed',
      label: 'BLOCKED SERIOUS',
      blinkMs: [1500, 3600],
      doubleBlinkChance: 0.22,
      lid: 0.24,
      squint: 0.34,
      pupilScale: 0.78,
      irisScale: 0.96,
      browLeft: 'annoyed_left',
      browRight: 'annoyed_right',
      mouth: 'flat_tight',
      gazeTargets: ['forward_focus','side_eye_left','down_left','center','forward_focus'],
      gazeWeights: [4, 2, 1, 1, 3],
      gazeDwellMs: [1300, 2900],
      gazeProfile: { saccadeMs: [95, 145], dwellMs: [1300, 2900], holdJitterPx: 0.09 },
      breath: 0.32,
      breathHz: 0.62,
      tailSway: 0.28,
      tailHz: 0.32,
      wingFlap: 0.18,
      wingHz: 0.62,
      wingRestDeg: 1.10,
      wingAsymmetryDeg: -0.35,
      wingTwitch: 0.60,
      wingLineBoost: 0.07,
      helmetTiltDeg: 4,
      bodyDriftX: 0.45,
      bodyDriftY: 0.2,
      driftHz: 0.32,
      motionBudget: { calm: true, rootXMax: 0.75, rootYMax: 1.05, tiltMax: 0.90 },
      fxIntensity: 0.72,
      eyeGlow: 0.50,
      browOpacity: 0.44,
      autoIntentMode: 'face_only',
      auraOpacity: 0.24,
      orbit: 0.24,
      spark: 0.68,
      runeIntensity: 0.30,
      scanBeam: false,
      intentPool: ['skeptical_squint','side_eye_hold','glance_left','slow_blink'],
      intentWeights: [3, 2, 1, 1],
      intentEveryMs: [6500, 12000]
    },
    night_sleepy: {
      name: 'night_sleepy',
      label: 'NIGHT SLEEPY',
      blinkMs: [4500, 10500],
      doubleBlinkChance: 0.05,
      lid: 0.58,
      squint: 0.08,
      pupilScale: 0.94,
      irisScale: 1.00,
      browLeft: 'sleepy_low_left',
      browRight: 'sleepy_low_right',
      mouth: 'sleepy_line',
      gazeTargets: ['down','sleepy','center','down_left','down_right','down','center'],
      gazeWeights: [4, 3, 3, 1, 1, 4, 2],
      gazeDwellMs: [3600, 7600],
      gazeProfile: { saccadeMs: [125, 180], dwellMs: [3600, 7600], holdJitterPx: 0.05 },
      breath: 0.18,
      breathHz: 0.22,
      tailSway: 0.22,
      tailHz: 0.20,
      wingFlap: 0.08,
      wingHz: 0.25,
      wingRestDeg: -0.80,
      wingAsymmetryDeg: 0,
      wingTwitch: 0.05,
      wingLineBoost: -0.04,
      helmetTiltDeg: -2,
      bodyDriftX: 0.20,
      bodyDriftY: 0.0,
      driftHz: 0.18,
      motionBudget: { calm: true, rootXMax: 0.3, rootYMax: 1.0, tiltMax: 0.30 },
      fxIntensity: 0.32,
      eyeGlow: 0.24,
      browOpacity: 0.16,
      autoIntentMode: 'face_only',
      auraOpacity: 0.10,
      orbit: 0.16,
      spark: 0.08,
      runeIntensity: 0.08,
      scanBeam: false,
      intentPool: ['slow_double_blink','slow_blink','glance_left','glance_right','sleepy_yawn'],
      intentWeights: [3, 3, 1, 1, 1],
      intentEveryMs: [14000, 24000]
    },
    degraded_offline: {
      name: 'degraded_offline',
      label: 'DEGRADED OFFLINE',
      blinkMs: [5600, 9800],
      doubleBlinkChance: 0.04,
      lid: 0.36,
      squint: 0.06,
      pupilScale: 0.78,
      irisScale: 0.92,
      browLeft: 'worried_left',
      browRight: 'neutral_right',
      mouth: 'drowsy_droop',
      gazeTargets: BEHAVIOR_GAZE_GRAMMAR.degraded_offline,
      gazeWeights: [3, 5, 2, 1],
      gazeDwellMs: [3200, 6800],
      gazeProfile: { saccadeMs: [140, 210], dwellMs: [3200, 6800], holdJitterPx: 0.025 },
      breath: 0.16,
      breathHz: 0.18,
      tailSway: 0.10,
      tailHz: 0.16,
      wingFlap: 0.04,
      wingHz: 0.16,
      wingRestDeg: -0.65,
      wingAsymmetryDeg: -0.25,
      wingTwitch: 0.03,
      wingLineBoost: -0.06,
      helmetTiltDeg: -3,
      bodyDriftX: 0.10,
      bodyDriftY: 0.0,
      driftHz: 0.12,
      motionBudget: { calm: true, rootXMax: 0.22, rootYMax: 0.55, tiltMax: 0.25 },
      fxIntensity: 0.20,
      eyeGlow: 0.18,
      browOpacity: 0.12,
      autoIntentMode: 'face_only',
      auraOpacity: 0.08,
      orbit: 0.10,
      spark: 0.04,
      runeIntensity: 0.06,
      scanBeam: false,
      intentPool: ['slow_blink','glance_left'],
      intentWeights: [4, 1],
      intentEveryMs: [18000, 30000]
    }
  };

  const NUDGES = {
    glance_left: {
      label: 'glance left',
      duration: 1100,
      gaze: 'left',
      body: { x: 0, y: 0, tilt: 0 }
    },
    glance_right: {
      label: 'glance right',
      duration: 1100,
      gaze: 'right',
      body: { x: 0, y: 0, tilt: 0 }
    },
    glance_up_left: {
      label: 'glance up-left',
      duration: 1100,
      gaze: 'up_left'
    },
    brow_pop: {
      label: 'brow pop',
      duration: 850,
      browLeft: 'popped_left',
      browRight: 'popped_right',
      mouth: 'ohh_small',
      pupilDelta: 0.24,
      lidDelta: -0.12,
      body: { y: -3, tilt: 0 }
    },
    skeptical_squint: {
      label: 'skeptical squint',
      duration: 1300,
      browLeft: 'angry_left',
      browRight: 'angry_right',
      mouth: 'flat_tight',
      lidDelta: 0.26,
      pupilDelta: -0.22,
      gaze: 'forward_focus'
    },
    settle: {
      label: 'settle',
      duration: 900,
      browLeft: 'flat_left',
      browRight: 'flat_right',
      mouth: 'smile_small',
      lidDelta: 0.30,
      bodyBob: 2.0
    },
    tiny_perk: {
      label: 'tiny perk',
      duration: 900,
      browLeft: 'raised_left',
      browRight: 'raised_right',
      mouth: 'smile_small',
      pupilDelta: 0.14,
      gaze: 'up_left',
      body: { y: -4, tilt: -1 }
    },
    smug_nod: {
      label: 'smug nod',
      duration: 1200,
      browLeft: 'smug_arch_left',
      browRight: 'smug_arch_right',
      mouth: 'smile_smug',
      body: { y: 3, tilt: -3 }
    },
    side_eye_hold: {
      label: 'side-eye hold',
      duration: 1500,
      gaze: 'side_eye_left',
      browLeft: 'side_eye_squint_left',
      browRight: 'side_eye_squint_right',
      mouth: 'flat_tight',
      lidDelta: 0.10
    },
    dramatic_sigh: {
      label: 'dramatic sigh',
      duration: 1700,
      browLeft: 'worried_left',
      browRight: 'worried_right',
      mouth: 'frown_small',
      lidDelta: 0.20,
      sigh: true,
      body: { y: 3, tilt: 2 }
    },
    slow_double_blink: {
      label: 'slow double blink',
      duration: 1100,
      blink: 'double',
      lidDelta: 0.18
    },
    sleepy_yawn: {
      label: 'sleepy yawn',
      duration: 2200,
      mouth: 'yawn_oval',
      browLeft: 'sleepy_low_left',
      browRight: 'sleepy_low_right',
      lidDelta: 0.20,
      body: { y: 2 }
    },
    scan_sweep: {
      label: 'scan sweep',
      duration: 1100,
      gaze: 'down_right',
      scan: true,
      browLeft: 'squint_focused_left',
      browRight: 'squint_focused_right'
    },
    sigh_wave: {
      label: 'sigh wave',
      duration: 1500,
      gaze: 'side_eye_left',
      browLeft: 'worried_left',
      browRight: 'worried_right',
      mouth: 'frown_small',
      sigh: true,
      body: { y: 2, tilt: 4 }
    },
    sleep_drift: {
      label: 'sleep drift',
      duration: 1800,
      gaze: 'sleepy',
      mouth: 'sleepy_line',
      browLeft: 'sleepy_low_left',
      browRight: 'sleepy_low_right',
      body: { y: 6 }
    },
    slow_blink: {
      label: 'slow blink',
      duration: 1100,
      gaze: 'sleepy',
      blink: 'long',
      lidDelta: 0.10
    }
  };

  function pickWeighted(list, weights, rng) {
    const total = weights.reduce((a, b) => a + b, 0);
    let r = rng() * total;
    for (let i = 0; i < list.length; i++) {
      r -= weights[i];
      if (r <= 0) return list[i];
    }
    return list[list.length - 1];
  }

  window.HermesMascotV2States = {
    STATES,
    NUDGES,
    BROWS,
    MOUTH_PATHS,
    GAZE,
    GAZES: GAZE,
    BEHAVIOR_GAZE_GRAMMAR,
    BEHAVIOR_MOUTH_GRAMMAR,
    CONTEXTUAL_BLINK_GRAMMAR,
    pickWeighted
  };
})();
